# STAGE 1: BUILD 
FROM maven:3.9.4-eclipse-temurin-17 AS build
WORKDIR /app

# Copia prima solo pom.xml, così sfruttiamo la cache per le dipendenze
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copia il codice sorgente e lo compila
COPY src ./src

RUN mvn clean package 

# STAGE 2: RUN 
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# Copia solo il jar compilato nella build
COPY --from=build /app/target/*.jar app.jar

# User non-root per sicurezza
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

# Finché stiamo in locale, stacci
EXPOSE 8080 

ENTRYPOINT ["java", "-jar", "app.jar"]